/**
 * 物质中文名称词典（纯离线）
 * 将常用中文物质名 / 俗名映射为化学式。
 */
export const SUBSTANCE_ZH = {
  // 单质
  铁: 'Fe',
  铜: 'Cu',
  锌: 'Zn',
  镁: 'Mg',
  铝: 'Al',
  钠: 'Na',
  钾: 'K',
  钙: 'Ca',
  钡: 'Ba',
  银: 'Ag',
  金: 'Au',
  铅: 'Pb',
  锡: 'Sn',
  锰: 'Mn',
  镍: 'Ni',
  钨: 'W',
  汞: 'Hg',
  铂: 'Pt',
  氢气: 'H2',
  氧气: 'O2',
  氮气: 'N2',
  氯气: 'Cl2',
  碳: 'C',
  木炭: 'C',
  活性炭: 'C',
  硫: 'S',
  硫磺: 'S',
  磷: 'P',
  红磷: 'P',
  白磷: 'P',
  铁粉: 'Fe',
  铜粉: 'Cu',
  锌粒: 'Zn',
  水银: 'Hg',
  氨气: 'NH3',
  一氧化碳: 'CO',
  二氧化碳: 'CO2',
  二氧化硫: 'SO2',
  三氧化硫: 'SO3',
  二氧化氮: 'NO2',
  一氧化氮: 'NO',
  二氧化锰: 'MnO2',
  二氧化硅: 'SiO2',
  过氧化氢: 'H2O2',

  // 氧化物与常见俗名
  水: 'H2O',
  冰: 'H2O',
  双氧水: 'H2O2',
  生石灰: 'CaO',
  氧化钙: 'CaO',
  氧化钠: 'Na2O',
  氧化钾: 'K2O',
  氧化钡: 'BaO',
  氧化铜: 'CuO',
  氧化铁: 'Fe2O3',
  三氧化二铁: 'Fe2O3',
  四氧化三铁: 'Fe3O4',
  氧化铝: 'Al2O3',
  氧化镁: 'MgO',
  氧化锌: 'ZnO',
  三氧化钨: 'WO3',
  干冰: 'CO2',

  // 酸
  盐酸: 'HCl',
  氢氯酸: 'HCl',
  硫酸: 'H2SO4',
  稀硫酸: 'H2SO4',
  浓硫酸: 'H2SO4',
  硝酸: 'HNO3',
  稀硝酸: 'HNO3',
  碳酸: 'H2CO3',
  磷酸: 'H3PO4',
  氢硫酸: 'H2S',

  // 碱
  氢氧化钠: 'NaOH',
  烧碱: 'NaOH',
  火碱: 'NaOH',
  苛性钠: 'NaOH',
  氢氧化钾: 'KOH',
  氢氧化钙: 'Ca(OH)2',
  熟石灰: 'Ca(OH)2',
  消石灰: 'Ca(OH)2',
  石灰水: 'Ca(OH)2',
  石灰浆: 'Ca(OH)2',
  氢氧化钡: 'Ba(OH)2',
  氢氧化镁: 'Mg(OH)2',
  氢氧化铜: 'Cu(OH)2',
  氢氧化铁: 'Fe(OH)3',
  氢氧化亚铁: 'Fe(OH)2',
  氢氧化铝: 'Al(OH)3',
  氨水: 'NH3·H2O',

  // 盐
  氯化钠: 'NaCl',
  食盐: 'NaCl',
  氯化钾: 'KCl',
  氯化钡: 'BaCl2',
  氯化钙: 'CaCl2',
  氯化镁: 'MgCl2',
  氯化铝: 'AlCl3',
  氯化锌: 'ZnCl2',
  氯化铁: 'FeCl3',
  氯化亚铁: 'FeCl2',
  氯化铜: 'CuCl2',
  氯化银: 'AgCl',
  硫酸铜: 'CuSO4',
  硫酸铁: 'Fe2(SO4)3',
  硫酸亚铁: 'FeSO4',
  硫酸钠: 'Na2SO4',
  硫酸钾: 'K2SO4',
  硫酸钡: 'BaSO4',
  硫酸钙: 'CaSO4',
  硫酸镁: 'MgSO4',
  硫酸锌: 'ZnSO4',
  硫酸铝: 'Al2(SO4)3',
  硫酸银: 'Ag2SO4',
  硝酸银: 'AgNO3',
  硝酸钾: 'KNO3',
  硝酸钠: 'NaNO3',
  硝酸钡: 'Ba(NO3)2',
  硝酸钙: 'Ca(NO3)2',
  硝酸镁: 'Mg(NO3)2',
  硝酸铜: 'Cu(NO3)2',
  硝酸铁: 'Fe(NO3)3',
  硝酸汞: 'Hg(NO3)2',
  碳酸钙: 'CaCO3',
  石灰石: 'CaCO3',
  大理石: 'CaCO3',
  碳酸钠: 'Na2CO3',
  纯碱: 'Na2CO3',
  苏打: 'Na2CO3',
  碳酸氢钠: 'NaHCO3',
  小苏打: 'NaHCO3',
  碳酸钾: 'K2CO3',
  草木灰: 'K2CO3',
  碳酸钡: 'BaCO3',
  碳酸镁: 'MgCO3',
  碳酸银: 'Ag2CO3',
  碳酸铜: 'CuCO3',
  碱式碳酸铜: 'Cu2(OH)2CO3',
  铜绿: 'Cu2(OH)2CO3',
  碳酸氢钙: 'Ca(HCO3)2',
  碳酸氢铵: 'NH4HCO3',
  碳酸铵: '(NH4)2CO3',
  氯化铵: 'NH4Cl',
  硫酸铵: '(NH4)2SO4',
  硝酸铵: 'NH4NO3',
  高锰酸钾: 'KMnO4',
  氯酸钾: 'KClO3',
  硫酸氢钠: 'NaHSO4',
  磷酸二氢钙: 'Ca(H2PO4)2',

  // 结晶水合物
  胆矾: 'CuSO4·5H2O',
  蓝矾: 'CuSO4·5H2O',
  五水硫酸铜: 'CuSO4·5H2O',
  明矾: 'KAl(SO4)2·12H2O',
  石膏: 'CaSO4·2H2O',

  // 有机物
  甲烷: 'CH4',
  沼气: 'CH4',
  天然气: 'CH4',
  乙醇: 'C2H5OH',
  酒精: 'C2H5OH',
  葡萄糖: 'C6H12O6',
  醋酸: 'CH3COOH',
  乙酸: 'CH3COOH'
}

/** 中文名 -> 化学式 查询（支持精确匹配） */
export function resolveZhName(name) {
  const key = String(name || '').replace(/\s+/g, '')
  if (Object.prototype.hasOwnProperty.call(SUBSTANCE_ZH, key)) {
    return SUBSTANCE_ZH[key]
  }
  return null
}
